Task 1



In [ ]:
import numpy as np

# Create a 1D array of consecutive even numbers from 2 to 32
even_numbers = np.arange(2, 33, 2)

# Reshape the 1D array into a 4 x 4 ndarray
X = even_numbers.reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task 2

In [ ]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print("Original 5x5 ndarray:")
print(X)

print("\nOdd numbers using Boolean indexing:")
print(Y)


Original 5x5 ndarray:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd numbers using Boolean indexing:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task 3

In [ ]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray with consecutive columns
# where the first column is full of 1s, the second column is full of 2s, and so on.
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


Task 4

In [4]:
import numpy as np


x = np.random.random(1000)


x

array([0.05005198, 0.67656605, 0.06834457, 0.08908106, 0.75504548,
       0.64608397, 0.30718953, 0.50638834, 0.940677  , 0.60668564,
       0.4322028 , 0.66050823, 0.02626498, 0.93462412, 0.47221166,
       0.03479007, 0.40685505, 0.72723802, 0.60682936, 0.77311321,
       0.017803  , 0.67153421, 0.36429446, 0.33546557, 0.72367875,
       0.84164708, 0.22955088, 0.83758395, 0.41050563, 0.24342319,
       0.18926268, 0.92500964, 0.90885756, 0.6433011 , 0.711159  ,
       0.72202565, 0.41062133, 0.74784703, 0.2149956 , 0.12290929,
       0.43321216, 0.45281456, 0.93193645, 0.66601798, 0.52273007,
       0.85059376, 0.96589879, 0.36258659, 0.761246  , 0.0545543 ,
       0.52567163, 0.61511458, 0.03158104, 0.52856961, 0.96098898,
       0.61284544, 0.94808684, 0.81676943, 0.91727539, 0.39424683,
       0.55460575, 0.79545477, 0.51417343, 0.46354175, 0.10529193,
       0.27583027, 0.89207755, 0.52728278, 0.95088163, 0.94970098,
       0.35177656, 0.73979977, 0.68772377, 0.58580784, 0.14143

In [5]:
v = np.eye(5)


v


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
b = np.diag(v)


b


array([1., 1., 1., 1., 1.])

In [7]:
n = np.diff(v)


n

array([[-1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.]])

In [8]:
m = np.arange(1,10)


m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.save("x_data",m)


s= np.random.randint(32)


s

14

In [10]:
r2array = np.append(n, [[5,5,5,4]], 0)


r2array

array([[-1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.],
       [ 5.,  5.,  5.,  4.]])

In [11]:
d = n[2:,:3]


d

array([[ 0.,  1., -1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [12]:
f = np.sort(r2array)


f


array([[-1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  1.],
       [-1.,  0.,  0.,  1.],
       [-1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 4.,  5.,  5.,  5.]])

In [13]:
array1 = np.array([1,5])
array2 = np.array([4,4,4])


np.add(array1,array2) # Broadcasting needed

ValueError: ignored

In [14]:
g = n.mean()


g

0.0

In [15]:
# import NumPy into Python

import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
lower_bound = 0
upper_bound = 5001
array_shape = (1000, 20)

X = np.random.randint(lower_bound, upper_bound, size=array_shape)

# print the shape of X
print("Shape of random_array:", X.shape)

Shape of random_array: (1000, 20)


In [16]:

# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

In [17]:
# Print the shape of ave_cols
print("Shape of column_averages:", ave_cols.shape)

# Print the shape of std_cols
print("Shape of column_stddevs:", std_cols.shape)

Shape of column_averages: (20,)
Shape of column_stddevs: (20,)


In [18]:
# Calculate the mean of each column
column_means = np.mean(X, axis=0)

# Mean normalize X
X_norm = X - column_means

In [19]:
# Print the average of all the values of X_norm
average_mean_normalized = np.mean(X_norm)

# Print the average of the minimum value in each column of X_norm
average_min_value = np.mean(np.min(X_norm, axis=0))

# Print the average of the maximum value in each column of X_norm
average_max_value = np.mean(np.max(X_norm, axis=0))


In [20]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([1, 4, 0, 2, 3])

In [21]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
random_permutation = np.random.permutation(X_norm.shape[0])

In [22]:
# Make any necessary calculations.

# Calculate the indices for splitting the data
train_size = int(0.6 * random_permutation.shape[0])
cross_val_size = int(0.2 * random_permutation.shape[0])

# You can save your calculations into variables to use later.

# Create a Training Set
X_train = X_norm[random_permutation[:train_size]]

# Create a Cross Validation Set
X_crossVal = X_norm[random_permutation[train_size : train_size + cross_val_size]]

# Create a Test Set
X_test = X_norm[random_permutation[train_size + cross_val_size:]]

In [23]:
# Print the shape of X_train
print("Shape of X_train:", X_train.shape)

# Print the shape of X_crossVal
print("Shape of X_crossVal:", X_crossVal.shape)

# Print the shape of X_test
print("Shape of X_test:", X_test.shape)

Shape of X_train: (600, 20)
Shape of X_crossVal: (200, 20)
Shape of X_test: (200, 20)


The End